# self reference to avoid users accidentally modifying important settings
spring.config.location=classpath:application.properties
# force servlet path for executable WAR, not used for a deployed WAR
server.servlet.context-path=/
# eagerly initialize default servlet
spring.mvc.servlet.load-on-startup=1
# servlet-relative URL for swagger specification
springfox.documentation.swagger.v2.path=/spec.json
# allow ssc circular dependencies in bean classes
spring.main.allow-circular-references=true
# SpringDoc OpenAPI configuration properties
# Output version overridden for compatibility (default=3.1)
springdoc.api-docs.path=/spec/openapi3.json
springdoc.api-docs.version=openapi_3_0
springdoc.writer-with-order-by-keys=true
springdoc.disable-i18n=true
springdoc.enable-groovy=false
springdoc.enable-hateoas=false
springdoc.enable-kotlin=false
springdoc.enable-spring-security=false

# as of 25.2.1, standard autoconfigured Actuator endpoints are not (and cannot be) used
management.endpoints.enabled-by-default=false

# annotation-based metrics via MetricsAspectsAutoConfiguration are not enabled or used
management.observations.annotations.enabled=false

# apply a global tag to all metrics
management.metrics.tags.application=SSC

# expose diskspace metrics for directories used by the application
management.metrics.system.diskspace.paths=${fortify.home},${user.home},${java.io.tmpdir},${catalina.base}/work

# expose quantiles metrics by default
management.metrics.distribution.percentiles.all=0.5,0.90,0.99

# see io.micrometer.core.instrument.distribution.DistributionStatisticConfig.DEFAULT for defaults
#management.metrics.distribution.expiry.all=PT2M
#management.metrics.distribution.buffer-length.all=3

# as of 25.2.1, less than 300 unique endpoints is exposed (method and path template combinations across all servlets)
# account for future new endpoints
management.metrics.web.server.max-uri-tags=400

# enable prometheus metrics export
management.prometheus.metrics.export.enabled=true
