CWE=false\:CWE
PCI\ 1.1=false\:PCI 1.1
PCI\ 1.2=false\:PCI 1.2
PCI\ 2.0=false\:PCI 2.0
OWASP\ Top\ Ten\ 2004=false\:OWASP Top Ten 2004
OWASP\ Top\ Ten\ 2007=false\:OWASP Top Ten 2007
OWASP\ Top\ Ten\ 2010=false\:OWASP Top Ten 2010
STIG\ 2=false\:STIG2
RTA\ Protected=false\:RTA Protected
FISMA=false\:FISMA
SANS\ 2009=false\:SANS 2009
SANS\ 2010=false\:SANS 2010
WASC\ 24+2=false\:WASC 24+2

