# Simple mappings of file extensions to com.fortify.frontend.meta.FileType
# These were intentionally omitted:
#      "sql" - can be SQL, TSQL, or PLSQL - bug 45957
#      "config"
#      "Config"
#      "settings" - due to bug 45957
#      "conf"
#      "cls" - can be VB6 or APEX

fileextensions.cs=CSHARP
fileextensions.vb=VB
fileextensions.cc=CPP
fileextensions.cpp=CPP
fileextensions.c++=CPP
fileextensions.h=C
fileextensions.m=OBJC
fileextensions.mm=OBJCPP
fileextensions.pch=OBJC
fileextensions.nst=NST
fileextensions.cob=COBOL
fileextensions.cbl=COBOL
fileextensions.java=JAVA
fileextensions.jsp=JSP
fileextensions.jspf=JSP
fileextensions.tag=JSP
fileextensions.tagx=JSP
fileextensions.tld=TLD
fileextensions.jspx=JSPX
fileextensions.xhtml=JSPX
fileextensions.faces=JSPX
fileextensions.jsff=JSPX
fileextensions.scala=SCALA
fileextensions.js=TYPESCRIPT
fileextensions.jsx=TYPESCRIPT
fileextensions.ts=TYPESCRIPT
fileextensions.tsx=TYPESCRIPT
fileextensions.php=PHP
fileextensions.phtml=PHP
fileextensions.ctp=PHP
fileextensions.py=PYTHON
fileextensions.htm=HTML
fileextensions.html=HTML
fileextensions.pks=PLSQL
fileextensions.pkh=PLSQL
fileextensions.pkb=PLSQL
fileextensions.xml=XML
fileextensions.xsd=XML
fileextensions.xmi=XML
fileextensions.wsdd=XML
fileextensions.cpx=XML
fileextensions.xcfg=XML
fileextensions.cscfg=XML
fileextensions.csdef=XML
fileextensions.wadcfg=XML
fileextensions.wadcfgx=XML
fileextensions.appxmanifest=XML
fileextensions.wsdl=XML
fileextensions.plist=XML
fileextensions.json=JSON
fileextensions.yaml=YAML
fileextensions.yml=YAML
fileextensions.properties=JAVA_PROPERTIES
fileextensions.ini=JAVA_PROPERTIES
fileextensions.cfm=CFML
fileextensions.cfml=CFML
fileextensions.cfc=CFML
fileextensions.exe=MSIL
fileextensions.dll=MSIL
fileextensions.winmd=MSIL
fileextensions.mod=MSIL
fileextensions.mdl=MSIL
fileextensions.baml=MSIL
fileextensions.aspx=ASPNET
fileextensions.ascx=ASPNET
fileextensions.asax=ASPNET
fileextensions.ashx=ASPNET
fileextensions.asmx=ASPNET
fileextensions.master=ASPNET
fileextensions.xaml=ASPNET
fileextensions.cshtml=ASPNET
fileextensions.axml=ASPNET
fileextensions.asp=ASP
fileextensions.vbscript=VBSCRIPT
fileextensions.vbs=VBSCRIPT
fileextensions.bas=VB6
fileextensions.frm=VB6
fileextensions.ctl=VB6
fileextensions.abap=ABAP
fileextensions.bsp=ABAP
fileextensions.as=ACTIONSCRIPT
fileextensions.mxml=MXML
fileextensions.rb=RUBY
fileextensions.erb=RUBY_ERB
fileextensions.swift=SWIFT
fileextensions.page=VISUAL_FORCE
fileextensions.trigger=APEX_TRIGGER
fileextensions.class=BYTECODE
fileextensions.jar=ARCHIVE
fileextensions.bc=BITCODE
