# Canonical URL where SSC should be accessed including context name
# For example https://my.host:1234/ssc
host.url=

# If "true", enable HTTP Host header validation against host.url value
host.validation=false

# Absolute path to full text index directory on local filesystem
searchIndex.location=

# If "true", allow only access over secure transport and reject insecure requests
com.fortify.ssc.enforceSecureTransport=false

# The maximum number of permitted sessions a user can have open simultaneously
# Note: this will not have the expected effect in case of X509 and HTTP SSO. These pre-authentication
# schemes take control over full user logout by design and will keep user's authentication valid
# regardless of SSC session invalidation.
authentication.max.concurrent.logins=1

# Application version "Current State" delta period, in days
pv.currentstate.delta.period=7

# If parameter is "false" an application version's snapshot will not contain removed issues
pv.snapshot.include_removed_issues=true

# Upload limit on audit attachments in MB
upload.mb.limit.audit.attachment=3

# Upload limit on analysis results in MiB
# Value must not exceed 2049 (MiB)
upload.mb.limit.analysis.result=1024

# Upload limit on plugin size in MB
upload.mb.limit.plugin.bundle=20

# Upload limit on meta value attachment in MB
upload.mb.limit.meta.value.attachment=50

# Size of the job processing thread pool
jobs.threadCount=10

# Number of job processing threads reserved for data exports
job.numberOfDedicatedDataExports=2

# How many times the job can fail before failing permanently
jobs.maxRunAttempts=3

# Minimal value for password strength score acceptable for saving new password
password.strength.min.score=3

# Absolute path to password dictionary on local filesystem
password.strength.dictionary.location=

# If "true", local password authentication is allowed when SSO is active
# Currently affects only X.509
# Other SSO methods never prevents local password authentication
sso.localAuthenticationEnabled=false

# If "true", SSC will use name of the auditor who audited issues last time in conflict
# resolution comments
# Otherwise conflict resolution strategy name will be used as a name for such comments
use.last.auditor.name.for.conflict.resolution.comments=false

# If "true", SSC will store the ldap cache in the database for faster startup. Otherwise
# any persisted cache will be removed.
ldap.cache.persistence.enabled=true

# If "true", SSC will store copies of user photos in the persisted store. Disable for faster
# startup. If enabled with ldap settings user photos will be available after the first
# periodic ldap cache refresh.
ldap.cache.persistence.userPhotos.enabled=false

# If "true", SSC will store the change histories of scan attribute values for every issue in uploaded scans.
# This adds a processing step in the artifact upload process.
issue.attrChangelog.enabled=false

# If "true", enable collection of JVM and SSC runtime metrics and expose them
# at "${host.url}/actuator/prometheus" in Prometheus or OpenMetrics scrape format.
# An API key in "X-Metrics-Api-Key" header is required for authentication.
# See "actuator.metrics.apiKeyFile".
actuator.metrics.enabled=false

# Absolute path to a file containing API key for SSC metrics endpoint.
# Required if "actuator.metrics.enabled" is "true".
# The file must contain a single line with the API key. The API key must
# match the following regular expression: ^[A-Za-z0-9_-]{32,256}$
actuator.metrics.apiKeyFile=
