# Enforce adding default protocol port to the host.url.
# Intended as a workaround for external services integration issues.
host.url.normalization.forcePort=false

# Enable lower-casing of host in the host.url.
# Disable to restore behavior before SSC version 23.1.0.
host.url.normalization.lowerCaseHost=true
