hibernate-search.indexer.type = SCROLL
hibernate-search.indexer.scroll.batchSize = 10000
# maximum number of expressions in a list for oracle is 1000:
hibernate-search.indexer.mass.batchSize = 1000
hibernate-search.indexer.updateThreadCount = 1
