# Configure if s3 plugin should be enabled
objectstorage.s3.enabled = false

# Configure the name of bucket in S3
objectstorage.s3.bucketName =

# Configure S3 endpoint URL
objectstorage.s3.endpointUrl =

# Configure S3 region
objectstorage.s3.region =

# Configure the path to AWS credentials file with only one profile section
objectstorage.s3.credentialsFile =

# Configure connection timeout for the S3 API, must be between 1s and 10m
objectstorage.s3.connectTimeoutSeconds = 10s

# Configure write timeout for the S3 API, must be between 1s and 10m
objectstorage.s3.writeTimeoutSeconds = 1m

# Configure read timeout for the S3 API, must be between 1s and 10m
objectstorage.s3.readTimeoutSeconds = 1m

# Configure S3 multipart upload part size, must be between 5MB and 5GB
# Note, each upload requires at least partSizeMB of JVM heap memory.
objectstorage.s3.partSizeMB = 10MB
