#Require the issue audit permission to upload audited analysis files.
auditedAnalysisRule.enabled=true

#Disallow upload of analysis results that change values of hidden tags
hiddenTagAuditsAnalysisRule.enabled=false

#Require approval if the Build Project is different between scans.
buildProjectProcessingRule.enabled=true

#Check external metadata file versions in scan against versions on server.
externalListVersionProcessingRule.enabled=true

#Require approval if file count differs.
processingrule.filecount.increase.enabled=true
processingrule.filecount.increase.percentage=10
processingrule.filecount.decrease.enabled=true
processingrule.filecount.decrease.percentage=10
processingrule.filecount.threshold=1

#Require approval if line count differs.
processingrule.linecount.increase.enabled=true
processingrule.linecount.increase.percentage=10
processingrule.linecount.decrease.enabled=true
processingrule.linecount.decrease.percentage=10
processingrule.linecount.threshold=1

#Automatically perform Instance ID migration on upload.
migrationProcessingRule.enabled=true

#Perform Force Instance ID migration on upload
forceMigrationProcessingRule.enabled=false

#Require approval if the engine version of a scan is newer than the engine version of the previous scan.
newerEngineVersionProcessingRule.enabled=false

#Disallow upload of analysis results if there is one pending approval.
pendingApprovalChecker.enabled=false

#Ignore SCA Scans performed in QuickScan mode.
quickScanProcessingRule.enabled=true

#Require approval if the rulepacks used in the scan do not match the rulepacks used in the previous scan.
rulePackVersionProcessingRule.enabled=false

#Require approval if the rulepacks used in the scan are older than the rulepacks loaded in SSC
sscRulePackVersionMatchProcessingRule.enabled=false

#Warn if audit information includes unknown custom tag.
unknownOrDisallowedAuditedAttrChecker.enabled=true

#Require approval if SCA or WebInspect scan does not have valid certification.
validCertificationProcessingRule.enabled=false

#Require approval if result has analysis warnings.
warningProcessingRule.enabled=false

#Require approval if result has Fortify Java Annotations
annotationsProcessingRule.enabled=false

#Disallow cascading scan approvals
vetoCascadingApprovalProcessingRule.enabled=false
