# Configuration settings for the REST API

rest.debug.includeStackTrace=false

# The older params ('viewby', 'ldaptype') of this api were not well-defined and were confusing to use.
# Legacy params support is currently enabled by default but may be disabled in future releases.
rest.ldapObjects.params.legacy.enable=true

# Configure maximum allowed size for JSON requests (10 MB)
rest.request.maxJsonSize=10485760

# backward compatibility option: if true, generate timestrings with offset like "+1234" instead of the default "+12:34"
# there is also a parallel property for webhooks payloads: "webhooks.sender.useLegacyTimeZoneOffsetFormat"
rest.response.useLegacyTimeZoneOffsetFormat=false

# parser version for REST API "q" query parameter, applies only to classic search, not full-text
# supported versions: 1 (default before 21.2; deprecated), 2 (default since 21.2)
rest.searchQueryParser.version=2

# The CREATE method on the issue-attachment-of-issue-controller REST API has been deprecated.  It will be removed in the future.
rest.enableLegacyCreateAttachmentEndpoint=false
