###########################################################
# Properties required for Spring seed context to start    #
# Loaded by com.fortify.ssc.init.SeedContextProvider  #
###########################################################

relative.session.timeout.minutes=30
absolute.session.timeout.minutes=240

authentication.max_failed_login_attempts=3
authentication.days_password_valid=30
authentication.minutes_user_frozen=30

runtime.federation.enabled=false
runtime.strict.certificate.checking=false


email.enabled=false
email.server.port=25
email.server=
email.server.username=
email.server.password=
email.server.secure.connection.enabled=false
email.server.ssl.trustHostCertificate=false
email.default.encoding=

job.cleanExecutedAfter.days=1

# unable to exclude com.fortify.manager.service.fulltext.LdapIndexHelper.LdapIndexTaskExecutor from component scan
hibernate-search.indexer.updateThreadCount=1

display.user.details = false

events.to.issues.max.events = 5

# RulepackBLL should be split to RulepackUpdateBLL and RulepackBLL
# where RulepackUpdateBLL could be excluded in seedContext.xml
# OR load these properties when needed not when bean is instantiated
rulepack.update.url=
rulepack.update.proxy.host=
rulepack.update.proxy.port=
rulepack.update.proxy.username=
rulepack.update.proxy.password=
rulepack.update.locale=